"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CheckLocationToolInstance = exports.InstantLocateToolInstance = exports.FindDentistsToolInstance = exports.FindClinicsToolInstance = exports.FindPharmaciesToolInstance = exports.FindHospitalsWithRouteToolInstance = exports.GetDistanceToolInstance = exports.CalculateRouteToolInstance = exports.GeocodeLocationToolInstance = exports.FindNearbyFacilitiesToolInstance = exports.PatientIdToolInstance = void 0;
const PatientIdTool_1 = require("./PatientIdTool");
Object.defineProperty(exports, "PatientIdToolInstance", { enumerable: true, get: function () { return PatientIdTool_1.PatientIdToolInstance; } });
const FindNearbyFacilitiesTool_1 = require("./FindNearbyFacilitiesTool");
Object.defineProperty(exports, "FindNearbyFacilitiesToolInstance", { enumerable: true, get: function () { return FindNearbyFacilitiesTool_1.FindNearbyFacilitiesToolInstance; } });
const GeocodeLocationTool_1 = require("./GeocodeLocationTool");
Object.defineProperty(exports, "GeocodeLocationToolInstance", { enumerable: true, get: function () { return GeocodeLocationTool_1.GeocodeLocationToolInstance; } });
const CalculateRouteTool_1 = require("./CalculateRouteTool");
Object.defineProperty(exports, "CalculateRouteToolInstance", { enumerable: true, get: function () { return CalculateRouteTool_1.CalculateRouteToolInstance; } });
const GetDistanceTool_1 = require("./GetDistanceTool");
Object.defineProperty(exports, "GetDistanceToolInstance", { enumerable: true, get: function () { return GetDistanceTool_1.GetDistanceToolInstance; } });
const FindHospitalsWithRouteTool_1 = require("./FindHospitalsWithRouteTool");
Object.defineProperty(exports, "FindHospitalsWithRouteToolInstance", { enumerable: true, get: function () { return FindHospitalsWithRouteTool_1.FindHospitalsWithRouteToolInstance; } });
const FindPharmaciesTool_1 = require("./FindPharmaciesTool");
Object.defineProperty(exports, "FindPharmaciesToolInstance", { enumerable: true, get: function () { return FindPharmaciesTool_1.FindPharmaciesToolInstance; } });
const FindClinicsTool_1 = require("./FindClinicsTool");
Object.defineProperty(exports, "FindClinicsToolInstance", { enumerable: true, get: function () { return FindClinicsTool_1.FindClinicsToolInstance; } });
const FindDentistsTool_1 = require("./FindDentistsTool");
Object.defineProperty(exports, "FindDentistsToolInstance", { enumerable: true, get: function () { return FindDentistsTool_1.FindDentistsToolInstance; } });
const InstantLocateTool_1 = require("./InstantLocateTool");
Object.defineProperty(exports, "InstantLocateToolInstance", { enumerable: true, get: function () { return InstantLocateTool_1.InstantLocateToolInstance; } });
const CheckLocationTool_1 = require("./CheckLocationTool");
Object.defineProperty(exports, "CheckLocationToolInstance", { enumerable: true, get: function () { return CheckLocationTool_1.CheckLocationToolInstance; } });
